/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Shop API
 * API for managing orders and menu in a coffee shop.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@coffeshop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MenuItemPromotionOneOf } from './MenuItemPromotionOneOf';
import {
    instanceOfMenuItemPromotionOneOf,
    MenuItemPromotionOneOfFromJSON,
    MenuItemPromotionOneOfFromJSONTyped,
    MenuItemPromotionOneOfToJSON,
} from './MenuItemPromotionOneOf';
import type { MenuItemPromotionOneOf1 } from './MenuItemPromotionOneOf1';
import {
    instanceOfMenuItemPromotionOneOf1,
    MenuItemPromotionOneOf1FromJSON,
    MenuItemPromotionOneOf1FromJSONTyped,
    MenuItemPromotionOneOf1ToJSON,
} from './MenuItemPromotionOneOf1';

/**
 * @type MenuItemPromotion
 * Details of the promotion applied to the menu item
 * @export
 */
export type MenuItemPromotion = MenuItemPromotionOneOf | MenuItemPromotionOneOf1;

export function MenuItemPromotionFromJSON(json: any): MenuItemPromotion {
    return MenuItemPromotionFromJSONTyped(json, false);
}

export function MenuItemPromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemPromotion {
    if (json == null) {
        return json;
    }
    if (instanceOfMenuItemPromotionOneOf(json)) {
        return MenuItemPromotionOneOfFromJSONTyped(json, true);
    }
    if (instanceOfMenuItemPromotionOneOf1(json)) {
        return MenuItemPromotionOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function MenuItemPromotionToJSON(json: any): any {
    return MenuItemPromotionToJSONTyped(json, false);
}

export function MenuItemPromotionToJSONTyped(value?: MenuItemPromotion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfMenuItemPromotionOneOf(value)) {
        return MenuItemPromotionOneOfToJSON(value as MenuItemPromotionOneOf);
    }
    if (instanceOfMenuItemPromotionOneOf1(value)) {
        return MenuItemPromotionOneOf1ToJSON(value as MenuItemPromotionOneOf1);
    }

    return {};
}

