/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Shop API
 * API for managing orders and menu in a coffee shop.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@coffeshop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuItemModifiersInner
 */
export interface MenuItemModifiersInner {
    /**
     * Name of the modifier
     * @type {string}
     * @memberof MenuItemModifiersInner
     */
    name: string;
    /**
     * Possible options for the modifier
     * @type {Set<string>}
     * @memberof MenuItemModifiersInner
     */
    options: Set<string>;
}

/**
 * Check if a given object implements the MenuItemModifiersInner interface.
 */
export function instanceOfMenuItemModifiersInner(value: object): value is MenuItemModifiersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function MenuItemModifiersInnerFromJSON(json: any): MenuItemModifiersInner {
    return MenuItemModifiersInnerFromJSONTyped(json, false);
}

export function MenuItemModifiersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemModifiersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'options': new Set(json['options']),
    };
}

export function MenuItemModifiersInnerToJSON(json: any): MenuItemModifiersInner {
    return MenuItemModifiersInnerToJSONTyped(json, false);
}

export function MenuItemModifiersInnerToJSONTyped(value?: MenuItemModifiersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'options': Array.from(value['options'] as Set<any>),
    };
}

